name: test

on: push

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Install Ginkgo v2
        run: go install github.com/onsi/ginkgo/v2/ginkgo@latest
      - name: Test
        run: ginkgo ./...
